### ISSUE TITLE
Coin lost

### ISSUE THREAD

**Issue by mukadodol** [italocoin-project/italo-gui#1]
Hi, 
Last night i mined italo coin, but balance never show on my gui wallet. It's 70s coins lost. When i used my exchange wallet, the balance show up normally. Can u help me ?

**Comment by italocoin-project** [comment]
Hello @mukadodol 

please try to reset the height from setings to 0, ti will make a full rescan of the wallet

![image](https://user-images.githubusercontent.com/12392580/51394256-37d0e180-1b3a-11e9-915a-7a74def6d045.png)

let me know if it works.

Regards,
Dev

**Comment by mukadodol** [comment]
Thx Dev, it works.

**Comment by italocoin-project** [comment]
@mukadodol glad that it works, i will fix it in next release; i will close it for now, reopen if you have the same issue.
